DROP TABLE IF EXISTS reimbursement_status;
DROP TABLE IF EXISTS reimbursement_type;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS reimbursements;


CREATE TABLE reimbursement_status (
	REIMB_STATUS_ID INTEGER PRIMARY KEY,
	REIMB_STATUS VARCHAR(10),


	CHECK (REIMB_STATUS IN ('Pending', 'Approved', 'Rejected'))
);

CREATE TABLE reimbursement_type (
	REIMB_TYPE_ID INTEGER PRIMARY KEY,
	REIMB_TYPE VARCHAR(10),
	
	CHECK (REIMB_TYPE IN('Lodging', 'Travel', 'Food', 'Other'))

);

CREATE TABLE user_roles (
	USER_ROLE_ID INTEGER PRIMARY KEY,
	USER_ROLE VARCHAR(50),
	
	CHECK (USER_ROLE IN('Finance Manager', ''))
);


CREATE TABLE reimbursements (
	REIMB_ID PRIMARY KEY,
	REIMB_AMOUNT INTEGER NOT NULL,
	REIMB_SUBMITTED TIMESTAMPTZ NOT NULL,
	REIMB_DESCRIPTION VARCHAR(250),
	REIMB_RECEIPT BYTEA NOT NULL,
	REIMB_AUTHOR INTEGER NOT NULL,
	REIMB_RESOLVER INTEGER NOT NULL,
	REIMB_STATUS_ID INTEGER NOT NULL,
	REIMB_TYPE_ID INTEGER NOT NULL,
	
	CONSTRAINT 



);